server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /mypages/**
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, /orderDetails/**
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: sms
          uri: http://localhost:8084
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://admin18-flower-order:8080
          predicates:
            - Path=/orders/**, /mypages/**
        - id: delivery
          uri: http://admin18-flower-delivery:8080
          predicates:
            - Path=/deliveries/**, /orderDetails/**
        - id: payment
          uri: http://admin18-flower-payment:8080
          predicates:
            - Path=/payments/** 
        - id: sms
          uri: http://admin18-flower-sms:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
